/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OcDBusAdaptor -a ocdbusadaptor.h:ocdbusadaptor.cpp de.buschmann23.ocNewsReader.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ocdbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class OcDBusAdaptor
 */

OcDBusAdaptor::OcDBusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

OcDBusAdaptor::~OcDBusAdaptor()
{
    // destructor
}

void OcDBusAdaptor::addFeed(const QStringList &feedUrl)
{
    // handle method call de.buschmann23.ocNewsReader.addFeed
    QMetaObject::invokeMethod(parent(), "addFeed", Q_ARG(QStringList, feedUrl));
}

void OcDBusAdaptor::showContent(const QStringList &itemId)
{
    // handle method call de.buschmann23.ocNewsReader.showContent
    QMetaObject::invokeMethod(parent(), "showContent", Q_ARG(QStringList, itemId));
}

