/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OcAccountAdaptor -a ocaccountadaptor.h:ocaccountadaptor.cpp de.buschmann23.ocNewsEngine.Account.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef OCACCOUNTADAPTOR_H
#define OCACCOUNTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface de.buschmann23.ocNewsEngine.Account
 */
class OcAccountAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "de.buschmann23.ocNewsEngine.Account")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"de.buschmann23.ocNewsEngine.Account\">\n"
"    <method name=\"create\"/>\n"
"    <method name=\"edit\"/>\n"
"  </interface>\n"
        "")
public:
    OcAccountAdaptor(QObject *parent);
    virtual ~OcAccountAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void create();
    void edit();
Q_SIGNALS: // SIGNALS
};

#endif
