/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OcAccountAdaptor -a ocaccountadaptor.h:ocaccountadaptor.cpp de.buschmann23.ocNewsEngine.Account.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ocaccountadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class OcAccountAdaptor
 */

OcAccountAdaptor::OcAccountAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

OcAccountAdaptor::~OcAccountAdaptor()
{
    // destructor
}

void OcAccountAdaptor::create()
{
    // handle method call de.buschmann23.ocNewsEngine.Account.create
    QMetaObject::invokeMethod(parent(), "create");
}

void OcAccountAdaptor::edit()
{
    // handle method call de.buschmann23.ocNewsEngine.Account.edit
    QMetaObject::invokeMethod(parent(), "edit");
}

