/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OcFoldersAdaptor -a ocfoldersadaptor.h:ocfoldersadaptor.cpp de.buschmann23.ocNewsEngine.Folders.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ocfoldersadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class OcFoldersAdaptor
 */

OcFoldersAdaptor::OcFoldersAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

OcFoldersAdaptor::~OcFoldersAdaptor()
{
    // destructor
}

void OcFoldersAdaptor::createFolder(const QString &name)
{
    // handle method call de.buschmann23.ocNewsEngine.Folders.createFolder
    QMetaObject::invokeMethod(parent(), "createFolder", Q_ARG(QString, name));
}

void OcFoldersAdaptor::deleteFolder(const QString &id)
{
    // handle method call de.buschmann23.ocNewsEngine.Folders.deleteFolder
    QMetaObject::invokeMethod(parent(), "deleteFolder", Q_ARG(QString, id));
}

QVariantMap OcFoldersAdaptor::getFolders()
{
    // handle method call de.buschmann23.ocNewsEngine.Folders.getFolders
    QVariantMap config;
    QMetaObject::invokeMethod(parent(), "getFolders", Q_RETURN_ARG(QVariantMap, config));
    return config;
}

void OcFoldersAdaptor::markFolderRead(const QString &id)
{
    // handle method call de.buschmann23.ocNewsEngine.Folders.markFolderRead
    QMetaObject::invokeMethod(parent(), "markFolderRead", Q_ARG(QString, id));
}

void OcFoldersAdaptor::renameFolder(const QString &id, const QString &name)
{
    // handle method call de.buschmann23.ocNewsEngine.Folders.renameFolder
    QMetaObject::invokeMethod(parent(), "renameFolder", Q_ARG(QString, id), Q_ARG(QString, name));
}

void OcFoldersAdaptor::requestFolders()
{
    // handle method call de.buschmann23.ocNewsEngine.Folders.requestFolders
    QMetaObject::invokeMethod(parent(), "requestFolders");
}

