/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OcGenericAdaptor -a ocgenericadaptor.h:ocgenericadaptor.cpp de.buschmann23.ocNewsEngine.Generic.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef OCGENERICADAPTOR_H
#define OCGENERICADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface de.buschmann23.ocNewsEngine.Generic
 */
class OcGenericAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "de.buschmann23.ocNewsEngine.Generic")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"de.buschmann23.ocNewsEngine.Generic\">\n"
"    <method name=\"getVersion\"/>\n"
"    <signal name=\"gotVersion\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"version\"/>\n"
"    </signal>\n"
"    <signal name=\"gotVersionError\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"error\"/>\n"
"    </signal>\n"
"    <method name=\"initConnection\"/>\n"
"    <signal name=\"initSuccess\"/>\n"
"    <signal name=\"initError\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"errorMessage\"/>\n"
"    </signal>\n"
"    <signal name=\"initErrorFlightMode\"/>\n"
"    <method name=\"quitEngine\"/>\n"
"  </interface>\n"
        "")
public:
    OcGenericAdaptor(QObject *parent);
    virtual ~OcGenericAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void getVersion();
    void initConnection();
    void quitEngine();
Q_SIGNALS: // SIGNALS
    void gotVersion(const QString &version);
    void gotVersionError(const QString &error);
    void initError(const QString &errorMessage);
    void initErrorFlightMode();
    void initSuccess();
};

#endif
