/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OcImageFetcherAdaptor -a ocimagefetcheradaptor.h:ocimagefetcheradaptor.cpp de.buschmann23.ocNewsEngine.ImageFetcher.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ocimagefetcheradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class OcImageFetcherAdaptor
 */

OcImageFetcherAdaptor::OcImageFetcherAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

OcImageFetcherAdaptor::~OcImageFetcherAdaptor()
{
    // destructor
}

int OcImageFetcherAdaptor::isFetchImagesRunning()
{
    // handle method call de.buschmann23.ocNewsEngine.ImageFetcher.isFetchImagesRunning
    int out0;
    QMetaObject::invokeMethod(parent(), "isFetchImagesRunning", Q_RETURN_ARG(int, out0));
    return out0;
}

