/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OcImageFetcherAdaptor -a ocimagefetcheradaptor.h:ocimagefetcheradaptor.cpp de.buschmann23.ocNewsEngine.ImageFetcher.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef OCIMAGEFETCHERADAPTOR_H
#define OCIMAGEFETCHERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface de.buschmann23.ocNewsEngine.ImageFetcher
 */
class OcImageFetcherAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "de.buschmann23.ocNewsEngine.ImageFetcher")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"de.buschmann23.ocNewsEngine.ImageFetcher\">\n"
"    <signal name=\"startedFetchingImages\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"numberOfItems\"/>\n"
"    </signal>\n"
"    <signal name=\"finishedFetchingImages\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"numberOfItems\"/>\n"
"    </signal>\n"
"    <signal name=\"fetchingImages\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"currentItem\"/>\n"
"    </signal>\n"
"    <method name=\"isFetchImagesRunning\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    OcImageFetcherAdaptor(QObject *parent);
    virtual ~OcImageFetcherAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int isFetchImagesRunning();
Q_SIGNALS: // SIGNALS
    void fetchingImages(const int &currentItem);
    void finishedFetchingImages(const int &numberOfItems);
    void startedFetchingImages(const int &numberOfItems);
};

#endif
