/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OcItemsAdaptor -a ocitemsadaptor.h:ocitemsadaptor.cpp de.buschmann23.ocNewsEngine.Items.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ocitemsadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class OcItemsAdaptor
 */

OcItemsAdaptor::OcItemsAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

OcItemsAdaptor::~OcItemsAdaptor()
{
    // destructor
}

void OcItemsAdaptor::markAllItemsRead()
{
    // handle method call de.buschmann23.ocNewsEngine.Items.markAllItemsRead
    QMetaObject::invokeMethod(parent(), "markAllItemsRead");
}

void OcItemsAdaptor::markItems(const QString &action, const QVariantList &ids)
{
    // handle method call de.buschmann23.ocNewsEngine.Items.markItems
    QMetaObject::invokeMethod(parent(), "markItems", Q_ARG(QString, action), Q_ARG(QVariantList, ids));
}

void OcItemsAdaptor::markItemsTillThis(const QString &action, const QDBusVariant &pubDate, const QDBusVariant &feedId)
{
    // handle method call de.buschmann23.ocNewsEngine.Items.markItemsTillThis
    QMetaObject::invokeMethod(parent(), "markItemsTillThis", Q_ARG(QString, action), Q_ARG(QDBusVariant, pubDate), Q_ARG(QDBusVariant, feedId));
}

void OcItemsAdaptor::requestItems(const QString &batchSize, const QString &offset, const QString &type, const QString &id, const QString &getRead)
{
    // handle method call de.buschmann23.ocNewsEngine.Items.requestItems
    QMetaObject::invokeMethod(parent(), "requestItems", Q_ARG(QString, batchSize), Q_ARG(QString, offset), Q_ARG(QString, type), Q_ARG(QString, id), Q_ARG(QString, getRead));
}

void OcItemsAdaptor::starItems(const QString &action, const QVariantMap &itemIds)
{
    // handle method call de.buschmann23.ocNewsEngine.Items.starItems
    QMetaObject::invokeMethod(parent(), "starItems", Q_ARG(QString, action), Q_ARG(QVariantMap, itemIds));
}

void OcItemsAdaptor::updateItems(const QString &lastModified, const QString &type, const QString &id)
{
    // handle method call de.buschmann23.ocNewsEngine.Items.updateItems
    QMetaObject::invokeMethod(parent(), "updateItems", Q_ARG(QString, lastModified), Q_ARG(QString, type), Q_ARG(QString, id));
}
