/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c OcFoldersIf -p ocfoldersif.h:ocfoldersif.cpp ../../ocNewsEngine/interfaces/de.buschmann23.ocNewsEngine.Folders.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "ocfoldersif.h"

/*
 * Implementation of interface class OcFoldersIf
 */

OcFoldersIf::OcFoldersIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OcFoldersIf::~OcFoldersIf()
{
}

