/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c OcImageFetcherIf -p ocimagefetcherif.h:ocimagefetcherif.cpp ../../../../engine/interfaces/de.buschmann23.ocNewsEngine.ImageFetcher.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OCIMAGEFETCHERIF_H
#define OCIMAGEFETCHERIF_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface de.buschmann23.ocNewsEngine.ImageFetcher
 */
class OcImageFetcherIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "de.buschmann23.ocNewsEngine.ImageFetcher"; }

public:
    OcImageFetcherIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OcImageFetcherIf();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<int> isFetchImagesRunning()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isFetchImagesRunning"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void fetchingImages(int currentItem);
    void finishedFetchingImages();
    void startedFetchingImages(int numberOfItems);
};

namespace de {
  namespace buschmann23 {
    namespace ocNewsEngine {
      typedef ::OcImageFetcherIf ImageFetcher;
    }
  }
}
#endif
