/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c OcImageFetcherIf -p ocimagefetcherif.h:ocimagefetcherif.cpp ../../../../engine/interfaces/de.buschmann23.ocNewsEngine.ImageFetcher.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "ocimagefetcherif.h"

/*
 * Implementation of interface class OcImageFetcherIf
 */

OcImageFetcherIf::OcImageFetcherIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OcImageFetcherIf::~OcImageFetcherIf()
{
}

