/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c OcItemsIf -p ocitemsif.h:ocitemsif.cpp ../../ocNewsEngine/interfaces/de.buschmann23.ocNewsEngine.Items.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "ocitemsif.h"

/*
 * Implementation of interface class OcItemsIf
 */

OcItemsIf::OcItemsIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OcItemsIf::~OcItemsIf()
{
}

